# From https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml
variables:
  REPO_NAME: git.mammoth.com.au/github/bl-cli
  GOPATH: /home/gitlab-runner/go

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet -composites=false ./commands/... ./bl/... ./pkg/... .
    - make test_unit

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - builds/bl
