contact_links:
  - name: BinaryLane Knowledge Base
    url: https://support.binarylane.com.au/support/home
    about: Documentation and tutorials on using BinaryLane services
  - name: BinaryLane Support
    url: https://support.binarylane.com.au/support/tickets/new
    about: Use BinaryLane Support for issues specific to your account
